# Generated by Django 5.2.3 on 2025-06-16 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventDetails',
            fields=[
                ('eventId', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=50, unique=True)),
                ('eventDescription', models.CharField(max_length=100)),
                ('eventDate', models.DateTimeField()),
                ('eventVenue', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='usersDetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('mobile', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='registrationDetails',
            fields=[
                ('registrationId', models.AutoField(primary_key=True, serialize=False)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.eventdetails')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.usersdetails')),
            ],
        ),
        migrations.CreateModel(
            name='membershipDetails',
            fields=[
                ('membershipCategory', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], max_length=20)),
                ('membershipId', models.AutoField(primary_key=True, serialize=False)),
                ('validity', models.DateField()),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mallusers.usersdetails')),
            ],
        ),
    ]
